name: Comment VRT Report
on:
  workflow_run:
    workflows: ["VRT"]
    types: [completed]
jobs:
  comment-vr-report:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Download playwright report
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: playwright-report
          path: playwright-report/
      - name: Comment PR
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        env:
          VRT_REPORT_PATH: ${{ github.workspace}}/playwright-results.json
        with:
          script: |
            const script = await import('${{ github.workspace }}/scripts/vrt-comment-pr.js');
            await script.default({ github, core, context });
